# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/ninonick0426/Linux_Unreal_Engine_5.6.1

TARGETS = \
	Unreal_QuadSim-Android-DebugGame  \
	Unreal_QuadSim-Android-Development  \
	Unreal_QuadSim-Android-Shipping  \
	Unreal_QuadSim-Linux-DebugGame  \
	Unreal_QuadSim-Linux-Development  \
	Unreal_QuadSim-Linux-Shipping  \
	Unreal_QuadSim-LinuxArm64-DebugGame  \
	Unreal_QuadSim-LinuxArm64-Development  \
	Unreal_QuadSim-LinuxArm64-Shipping  \
	Unreal_QuadSim \
	Unreal_QuadSimEditor-Linux-DebugGame  \
	Unreal_QuadSimEditor-Linux-Development  \
	Unreal_QuadSimEditor \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend Unreal_QuadSimEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug Unreal_QuadSimEditor-Linux-Debug


Unreal_QuadSim-Android-DebugGame:
	 $(BUILD) Unreal_QuadSim Android DebugGame  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim-Android-Development:
	 $(BUILD) Unreal_QuadSim Android Development  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim-Android-Shipping:
	 $(BUILD) Unreal_QuadSim Android Shipping  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim-Linux-DebugGame:
	 $(BUILD) Unreal_QuadSim Linux DebugGame  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim-Linux-Development:
	 $(BUILD) Unreal_QuadSim Linux Development  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim-Linux-Shipping:
	 $(BUILD) Unreal_QuadSim Linux Shipping  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim-LinuxArm64-DebugGame:
	 $(BUILD) Unreal_QuadSim LinuxArm64 DebugGame  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim-LinuxArm64-Development:
	 $(BUILD) Unreal_QuadSim LinuxArm64 Development  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim-LinuxArm64-Shipping:
	 $(BUILD) Unreal_QuadSim LinuxArm64 Shipping  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSim: Unreal_QuadSim-Linux-Development

Unreal_QuadSimEditor-Linux-DebugGame:
	 $(BUILD) Unreal_QuadSimEditor Linux DebugGame  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSimEditor-Linux-Development:
	 $(BUILD) Unreal_QuadSimEditor Linux Development  -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" $(ARGS)

Unreal_QuadSimEditor: Unreal_QuadSimEditor-Linux-Development

LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/ninonick0426/Desktop/Quadcopter/Unreal_QuadSim/Unreal_QuadSim.uproject" -Game 

.PHONY: $(TARGETS)
